// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.28.2
// source: matchengine.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MatchEngine_PutLimitOrder_FullMethodName  = "/matchengine.MatchEngine/PutLimitOrder"
	MatchEngine_PutMarketOrder_FullMethodName = "/matchengine.MatchEngine/PutMarketOrder"
	MatchEngine_CancelOrder_FullMethodName    = "/matchengine.MatchEngine/CancelOrder"
	MatchEngine_GetOrder_FullMethodName       = "/matchengine.MatchEngine/GetOrder"
	MatchEngine_GetOrderBook_FullMethodName   = "/matchengine.MatchEngine/GetOrderBook"
	MatchEngine_GetBalance_FullMethodName     = "/matchengine.MatchEngine/GetBalance"
	MatchEngine_ListAsset_FullMethodName      = "/matchengine.MatchEngine/ListAsset"
	MatchEngine_CreateMarket_FullMethodName   = "/matchengine.MatchEngine/CreateMarket"
	MatchEngine_CreateAsset_FullMethodName    = "/matchengine.MatchEngine/CreateAsset"
)

// MatchEngineClient is the client API for MatchEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MatchEngineClient interface {
	PutLimitOrder(ctx context.Context, in *PutLimitOrderRequest, opts ...grpc.CallOption) (*PutOrderResponse, error)
	PutMarketOrder(ctx context.Context, in *PutMarketOrderRequest, opts ...grpc.CallOption) (*PutOrderResponse, error)
	CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error)
	GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error)
	GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error)
	GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error)
	ListAsset(ctx context.Context, in *ListAssetRequest, opts ...grpc.CallOption) (*ListAssetResponse, error)
	CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error)
	CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error)
}

type matchEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewMatchEngineClient(cc grpc.ClientConnInterface) MatchEngineClient {
	return &matchEngineClient{cc}
}

func (c *matchEngineClient) PutLimitOrder(ctx context.Context, in *PutLimitOrderRequest, opts ...grpc.CallOption) (*PutOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutOrderResponse)
	err := c.cc.Invoke(ctx, MatchEngine_PutLimitOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) PutMarketOrder(ctx context.Context, in *PutMarketOrderRequest, opts ...grpc.CallOption) (*PutOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PutOrderResponse)
	err := c.cc.Invoke(ctx, MatchEngine_PutMarketOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) CancelOrder(ctx context.Context, in *CancelOrderRequest, opts ...grpc.CallOption) (*CancelOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CancelOrderResponse)
	err := c.cc.Invoke(ctx, MatchEngine_CancelOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetOrder(ctx context.Context, in *GetOrderRequest, opts ...grpc.CallOption) (*GetOrderResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderResponse)
	err := c.cc.Invoke(ctx, MatchEngine_GetOrder_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetOrderBook(ctx context.Context, in *GetOrderBookRequest, opts ...grpc.CallOption) (*GetOrderBookResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetOrderBookResponse)
	err := c.cc.Invoke(ctx, MatchEngine_GetOrderBook_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) GetBalance(ctx context.Context, in *GetBalanceRequest, opts ...grpc.CallOption) (*GetBalanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBalanceResponse)
	err := c.cc.Invoke(ctx, MatchEngine_GetBalance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) ListAsset(ctx context.Context, in *ListAssetRequest, opts ...grpc.CallOption) (*ListAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListAssetResponse)
	err := c.cc.Invoke(ctx, MatchEngine_ListAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) CreateMarket(ctx context.Context, in *CreateMarketRequest, opts ...grpc.CallOption) (*CreateMarketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateMarketResponse)
	err := c.cc.Invoke(ctx, MatchEngine_CreateMarket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *matchEngineClient) CreateAsset(ctx context.Context, in *CreateAssetRequest, opts ...grpc.CallOption) (*CreateAssetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateAssetResponse)
	err := c.cc.Invoke(ctx, MatchEngine_CreateAsset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MatchEngineServer is the server API for MatchEngine service.
// All implementations must embed UnimplementedMatchEngineServer
// for forward compatibility.
type MatchEngineServer interface {
	PutLimitOrder(context.Context, *PutLimitOrderRequest) (*PutOrderResponse, error)
	PutMarketOrder(context.Context, *PutMarketOrderRequest) (*PutOrderResponse, error)
	CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error)
	GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error)
	GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error)
	GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error)
	ListAsset(context.Context, *ListAssetRequest) (*ListAssetResponse, error)
	CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error)
	CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error)
	mustEmbedUnimplementedMatchEngineServer()
}

// UnimplementedMatchEngineServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMatchEngineServer struct{}

func (UnimplementedMatchEngineServer) PutLimitOrder(context.Context, *PutLimitOrderRequest) (*PutOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutLimitOrder not implemented")
}
func (UnimplementedMatchEngineServer) PutMarketOrder(context.Context, *PutMarketOrderRequest) (*PutOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutMarketOrder not implemented")
}
func (UnimplementedMatchEngineServer) CancelOrder(context.Context, *CancelOrderRequest) (*CancelOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CancelOrder not implemented")
}
func (UnimplementedMatchEngineServer) GetOrder(context.Context, *GetOrderRequest) (*GetOrderResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrder not implemented")
}
func (UnimplementedMatchEngineServer) GetOrderBook(context.Context, *GetOrderBookRequest) (*GetOrderBookResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetOrderBook not implemented")
}
func (UnimplementedMatchEngineServer) GetBalance(context.Context, *GetBalanceRequest) (*GetBalanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBalance not implemented")
}
func (UnimplementedMatchEngineServer) ListAsset(context.Context, *ListAssetRequest) (*ListAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListAsset not implemented")
}
func (UnimplementedMatchEngineServer) CreateMarket(context.Context, *CreateMarketRequest) (*CreateMarketResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateMarket not implemented")
}
func (UnimplementedMatchEngineServer) CreateAsset(context.Context, *CreateAssetRequest) (*CreateAssetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateAsset not implemented")
}
func (UnimplementedMatchEngineServer) mustEmbedUnimplementedMatchEngineServer() {}
func (UnimplementedMatchEngineServer) testEmbeddedByValue()                     {}

// UnsafeMatchEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MatchEngineServer will
// result in compilation errors.
type UnsafeMatchEngineServer interface {
	mustEmbedUnimplementedMatchEngineServer()
}

func RegisterMatchEngineServer(s grpc.ServiceRegistrar, srv MatchEngineServer) {
	// If the following call panics, it indicates UnimplementedMatchEngineServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MatchEngine_ServiceDesc, srv)
}

func _MatchEngine_PutLimitOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutLimitOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).PutLimitOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_PutLimitOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).PutLimitOrder(ctx, req.(*PutLimitOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_PutMarketOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutMarketOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).PutMarketOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_PutMarketOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).PutMarketOrder(ctx, req.(*PutMarketOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_CancelOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CancelOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).CancelOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_CancelOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).CancelOrder(ctx, req.(*CancelOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetOrder_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetOrder(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_GetOrder_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetOrder(ctx, req.(*GetOrderRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetOrderBook_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetOrderBookRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetOrderBook(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_GetOrderBook_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetOrderBook(ctx, req.(*GetOrderBookRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_GetBalance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBalanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).GetBalance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_GetBalance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).GetBalance(ctx, req.(*GetBalanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_ListAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).ListAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_ListAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).ListAsset(ctx, req.(*ListAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_CreateMarket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateMarketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).CreateMarket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_CreateMarket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).CreateMarket(ctx, req.(*CreateMarketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MatchEngine_CreateAsset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateAssetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MatchEngineServer).CreateAsset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MatchEngine_CreateAsset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MatchEngineServer).CreateAsset(ctx, req.(*CreateAssetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MatchEngine_ServiceDesc is the grpc.ServiceDesc for MatchEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MatchEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "matchengine.MatchEngine",
	HandlerType: (*MatchEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutLimitOrder",
			Handler:    _MatchEngine_PutLimitOrder_Handler,
		},
		{
			MethodName: "PutMarketOrder",
			Handler:    _MatchEngine_PutMarketOrder_Handler,
		},
		{
			MethodName: "CancelOrder",
			Handler:    _MatchEngine_CancelOrder_Handler,
		},
		{
			MethodName: "GetOrder",
			Handler:    _MatchEngine_GetOrder_Handler,
		},
		{
			MethodName: "GetOrderBook",
			Handler:    _MatchEngine_GetOrderBook_Handler,
		},
		{
			MethodName: "GetBalance",
			Handler:    _MatchEngine_GetBalance_Handler,
		},
		{
			MethodName: "ListAsset",
			Handler:    _MatchEngine_ListAsset_Handler,
		},
		{
			MethodName: "CreateMarket",
			Handler:    _MatchEngine_CreateMarket_Handler,
		},
		{
			MethodName: "CreateAsset",
			Handler:    _MatchEngine_CreateAsset_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "matchengine.proto",
}
