server:
  host: "0.0.0.0"
  port: 7316

database:
  host: "127.0.0.1"
  port: 3306
  name: "trade_log"
  username: "root"
  password: ""
  max_open: 100
  max_idle: 50

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

kafka:
  brokers:
    - "127.0.0.1:9092"
  producer:
    topic: "orders"
  consumer:
    group: "matchengine"
    topic: "deals"
    offset: "newest"