server:
  host: "0.0.0.0"
  port: 4444
  shutdown_timeout: 30

log:
  file: "alertcenter.log"
  max_size: 104857600
  max_backups: 7
  max_age: 7

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  sentinel:
    enabled: true
    master: "mymaster"
    addrs:
      - "127.0.0.1:26379"
      - "127.0.0.1:26380"
      - "127.0.0.1:26381"