server:
  host: "0.0.0.0"
  port: 9066

workers: 4

backend:
  matchengine: "127.0.0.1:7316"
  marketprice: "127.0.0.1:7416"
  readhistory: "127.0.0.1:7424"

monitor:
  bind: ":8081"

alert:
  host: "alertcenter"
  port: 4444