server:
  host: "127.0.0.1"
  port: 7424

database:
  host: "127.0.0.1"
  port: 3306
  name: "trade_history"
  username: "root"
  password: "qq851126"
  max_open: 100
  max_idle: 50

workers: 10

alert:
  host: "alertcenter"
  port: 4444