server:
  host: "0.0.0.0"
  port: 8081
  worker_num: 4

matchengine:
  host: "127.0.0.1"
  port: 7316
  timeout: 1.0

marketprice:
  host: "127.0.0.1"
  port: 7416
  timeout: 1.0

readhistory:
  host: "127.0.0.1"
  port: 7424
  timeout: 1.0

kafka:
  brokers:
    - "127.0.0.1:9092"
  consumer:
    orders_topic: "orders"
    balances_topic: "balances"
    group: "accessws"

auth_url: "http://127.0.0.1:8000/internal/exchange/user/auth"
sign_url: "http://127.0.0.1:8000/internal/exchange/user/api/auth"

cache_timeout: 10.0

intervals:
  depth: 0.5
  price: 0.5
  kline: 0.5
  deals: 0.5
  state: 0.5
  today: 0.5
