server:
  host: "0.0.0.0"
  port: 4444

redis:
  host: "127.0.0.1"
  port: 6379
  password: "123456"
  db: 0
  sentinel:
    enabled: true
    master: "mymaster"
    addrs:
      - "127.0.0.1:26379"
      - "127.0.0.1:26380"
      - "127.0.0.1:26381"