server:
  host: "127.0.0.1"
  port: 7416

kafka:
  brokers:
    - "127.0.0.1:9092"
  consumer:
    topic: "deals"
    group: "marketprice"
    offset: "newest"

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100